/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Petstore
 * Petstore
 * OpenAPI spec version: 0.1.0
 */
export type PetType = (typeof PetType)[keyof typeof PetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetType = {
  DOG: 'DOG',
  CAT: 'CAT',
} as const;

export type PetListParams = {
  /**
   * Pet type
   */
  type?: PetType;
};

export interface Pet {
  /** @nullable */
  breed: string | null;
  /** @nullable */
  dateOfBirth: string | null;
  /** @nullable */
  id: number | null;
  name: string;
  type: PetType;
  /** @nullable */
  weight: number | null;
}
