/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Petstore
 * Petstore
 * OpenAPI spec version: 0.1.0
 */
import { Hono } from 'hono';

import { petCreateHandlers } from './handlers/petCreate';
import { petListHandlers } from './handlers/petList';
import { petRetrieveHandlers } from './handlers/petRetrieve';
import { petUpdateHandlers } from './handlers/petUpdate';
import { petDeleteHandlers } from './handlers/petDelete';

const app = new Hono();

/**
 * Create a pet
 * @summary Create pet
 */

app.post('/pets', ...petCreateHandlers);

/**
 * List all pets
 * @summary List pets
 */

app.get('/pets', ...petListHandlers);

/**
 * Retrieve a single pet
 * @summary Retrieve pet
 */

app.get('/pets/:petId', ...petRetrieveHandlers);

/**
 * Update a pet
 * @summary Update pet
 */

app.put('/pets/:petId', ...petUpdateHandlers);

/**
 * Delete a pet
 * @summary Delete pet
 */

app.delete('/pets/:petId', ...petDeleteHandlers);

export default app;
