/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Petstore
 * Petstore
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const petCreateBody = zod.object({
  id: zod.number().nullable(),
  type: zod.enum(['DOG', 'CAT']),
  name: zod.string(),
  dateOfBirth: zod.date().nullable(),
  breed: zod.string().nullable(),
  weight: zod.number().nullable(),
});

export const petCreateResponse = zod
  .object({
    id: zod.number().nullable(),
    type: zod.enum(['DOG', 'CAT']),
    name: zod.string(),
    dateOfBirth: zod.date().nullable(),
    breed: zod.string().nullable(),
    weight: zod.number().nullable(),
  })
  .strict();

export const petListQueryParams = zod.object({
  type: zod.enum(['DOG', 'CAT']).optional(),
});

export const petListResponseItem = zod
  .object({
    id: zod.number().nullish(),
    type: zod.enum(['DOG', 'CAT']).optional(),
    name: zod.string().optional(),
    dateOfBirth: zod.date().nullish(),
    breed: zod.string().nullish(),
    weight: zod.number().nullish(),
  })
  .strict();
export const petListResponse = zod.array(petListResponseItem);

export const petRetrieveParams = zod.object({
  petId: zod.number(),
});

export const petRetrieveResponse = zod
  .object({
    id: zod.number().nullable(),
    type: zod.enum(['DOG', 'CAT']),
    name: zod.string(),
    dateOfBirth: zod.date().nullable(),
    breed: zod.string().nullable(),
    weight: zod.number().nullable(),
  })
  .strict();

export const petUpdateParams = zod.object({
  petId: zod.number(),
});

export const petUpdateBody = zod.object({
  id: zod.number().nullable(),
  type: zod.enum(['DOG', 'CAT']),
  name: zod.string(),
  dateOfBirth: zod.date().nullable(),
  breed: zod.string().nullable(),
  weight: zod.number().nullable(),
});

export const petUpdateResponse = zod
  .object({
    id: zod.number().nullable(),
    type: zod.enum(['DOG', 'CAT']),
    name: zod.string(),
    dateOfBirth: zod.date().nullable(),
    breed: zod.string().nullable(),
    weight: zod.number().nullable(),
  })
  .strict();

export const petDeleteParams = zod.object({
  petId: zod.number(),
});
