/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Petstore
 * Petstore
 * OpenAPI spec version: 0.1.0
 */
import type { Context, Env } from 'hono';

import { Pet, PetListParams, Pet } from './petstore.schemas';

export type PetCreateContext<E extends Env = any> = Context<E, '/pets', { in: { json: Pet } }>;
export type PetListContext<E extends Env = any> = Context<E, '/pets', { in: { query: PetListParams } }>;
export type PetRetrieveContext<E extends Env = any> = Context<
  E,
  '/pets/:petId',
  {
    in: {
      param: {
        petId: number;
      };
    };
  }
>;
export type PetUpdateContext<E extends Env = any> = Context<
  E,
  '/pets/:petId',
  {
    in: {
      param: {
        petId: number;
      };
      json: Pet;
    };
  }
>;
export type PetDeleteContext<E extends Env = any> = Context<
  E,
  '/pets/:petId',
  {
    in: {
      param: {
        petId: number;
      };
    };
  }
>;
